// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/amothic/boilerplate/adapter/controller"
	"github.com/amothic/boilerplate/adapter/persistence"
	"github.com/amothic/boilerplate/driver"
	"github.com/amothic/boilerplate/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer() (*driver.Server, error) {
	db, err := driver.OpenSQL()
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewUserRepository(db)
	userInteractor := usecase.NewUserInteractor(userRepository)
	userController := controller.NewUserController(userInteractor)
	server := driver.NewServer(userController)
	return server, nil
}

// wire.go:

var usecaseSet = wire.NewSet(usecase.NewUserInteractor)

var controllerSet = wire.NewSet(controller.NewUserController)

var persistenceSet = wire.NewSet(persistence.NewUserRepository)
